---
title: "PT.9 - 간단한 데이터 탐색 & 시각화"
description: "2023-2학기 튜터링"
author: "Sungil Park"
date: "2023/11/28"
---

```{r, include=FALSE}
rm(list = ls())
library(dplyr)
```

```{r}
which(iris[,1:4]>5.0)
```


```{r}
idx <- which(iris[,1:4]>5.0,arr.ind=TRUE)
idx[,1]
```


```{r}
#하단 내용 할줄 알아야함!
iris[idx[,1],]
iris[unique(idx[,1]),]
```


```{r}
#5 함수
favorite <- c('WINTER','SUMMER','SPRING','SUMMER','SUMMER','FALL','FALL','SUMMER','SPRING','SPRING')
favorite
```


```{r}
table(favorite)
length(favorite)

table(favorite)/length(favorite)
```


```{r}
ds <- table(favorite)
ds
```


```{r}
barplot(ds,main='favorite season')
```


```{r}
ds <- table(favorite)
ds
```


```{r}
pie(ds,main='favorite season')
```


```{r}
favorite.color <- c(2,3,2,1,1,2,2,1,3,2,1,3,2,1,2)

ds <- table(favorite.color)
colors <- c('green','red','blue')
names(ds) <- colors

ds
```


```{r}
barplot(ds,main='favorite color')
```


```{r}
barplot(ds,
        main='favorite color',
        col=colors)
```


```{r}
pie(ds,main='favorite colors',
    col=colors)
```


```{r}
#과제 2 1-4번 
#과제2) 1번 4) 문제  if, else if, else, for문 활용하세요.
#4) 중간고사 성적이 90점 이상은 A학점, 80점 이상은 B학점, 70점 이상은 C학점, 60점 이상은 D학점, 나머지는 F학점을 주려고 합니다. 해당 문제를 Code를 활용하여 풀어보세요.(if, else if, else, for문 활용)

weight <- c(60,62,64,65,68,69)
weight.heavy <- c(weight,120)
weight
weight.heavy
```




```{r}
mean(weight)
mean(weight.heavy)
```


```{r}
mean(weight,trim=0.2)
mean(weight.heavy,trim=0.2)
```


```{r}
median(weight)
median(weight.heavy)
```


```{r}
mydata <- c(60,62,64,65,68,69,120)
quantile(mydata)
quantile(mydata,(0:10)/10)
summary(mydata)
```


```{r}
mydata <- c(60,62,64,65,68,69,120)
var(mydata)
sd(mydata)
range(mydata)
diff(range(mydata))
```


```{r}
dist <- cars[,2]
hist(dist,
     main="Histogram for 제동거리",
     xlab="제동거리",
     ylab="빈도수",
     border = "blue",
     col="green",
     las=2,
     breaks=5)
```


## 과제

```{r}
weight <-c(45,55,65,75,86,74,67,98,50,66)
a <- character(length(weight))

for (i in 1:length(weight)) {
  if (weight[i] >= 90) {
    a[i] <- "A"
  } else if (weight[i] >= 80 & weight[i] < 90) {
    a[i] <- "B"
  } else if (weight[i] >= 70 & weight[i] < 80) {
    a[i] <- "C"
  } else if (weight[i] >= 60 & weight[i] < 70) {
    a[i] <- "D"
  } else {
    a[i] <- "F"
  }
}

a


ifelse(weight >= 90, "A", 
       ifelse(weight >= 80, "B",
              ifelse(weight >= 70, "C", 
                     ifelse(weight >= 60, "D","F"))))
```










